### ISSUE TITLE
NPE while shutting down the OSGi container

### ISSUE THREAD

**Issue by attila-kiss-it** [everit-org/ecm-component#3]
SEVERE: Component error: {id: 'hu.vivelab.bi.internal.auth.VivelabAuthenticatorComponent', state: STARTING, properties: {querydslSupport.target=, wrappedAuthenticator.target=, service.pid=hu.vivelab.bi.internal.auth.VivelabAuthenticatorComponent}}
    java.lang.NullPointerException: A null service reference is not allowed.
    	at org.eclipse.osgi.internal.framework.BundleContextImpl.getServiceObjects(BundleContextImpl.java:1036)
    	at org.everit.osgi.ecm.component.ri.internal.attribute.ServiceReferenceAttributeHelper.addToUsedServiceReferences(ServiceReferenceAttributeHelper.java:91)
    	at org.everit.osgi.ecm.component.ri.internal.attribute.ServiceReferenceAttributeHelper.bindInternal(ServiceReferenceAttributeHelper.java:124)
    	at org.everit.osgi.ecm.component.ri.internal.attribute.ReferenceHelper.bind(ReferenceHelper.java:200)
    	at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl.starting(ComponentContextImpl.java:709)
    	at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl.restart(ComponentContextImpl.java:670)
    	at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl.access$800(ComponentContextImpl.java:69)
    	at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl$ReferenceEventHandlerImpl.updateNonDynamic(ComponentContextImpl.java:158)
    	at org.everit.osgi.ecm.component.ri.internal.attribute.ReferenceHelper$ReferenceCapabilityConsumer.accept(ReferenceHelper.java:76)
    	at org.everit.osgi.capabilitycollector.AbstractCapabilityCollector.notifyConsumer(AbstractCapabilityCollector.java:222)
    	at org.everit.osgi.capabilitycollector.AbstractCapabilityCollector.removedCapability(AbstractCapabilityCollector.java:287)
    	at org.everit.osgi.capabilitycollector.ServiceReferenceCollector$ReferenceTrackerCustomizer.removedService(ServiceReferenceCollector.java:54)
    	at org.everit.osgi.capabilitycollector.ServiceReferenceCollector$ReferenceTrackerCustomizer.removedService(ServiceReferenceCollector.java:36)
    	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:967)
    	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
    	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
    	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:909)
    	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
    	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:914)
    	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
    	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
    	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:222)
    	at org.everit.osgi.ecm.component.ri.internal.ComponentServiceRegistration.unregister(ComponentServiceRegistration.java:56)
    	at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl.stopping(ComponentContextImpl.java:750)
    	at org.everit.osgi.ecm.component.ri.internal.ComponentContextImpl.close(ComponentContextImpl.java:298)
    	at org.everit.osgi.ecm.component.ri.internal.ComponentContainerImpl.close(ComponentContainerImpl.java:65)
    	at org.everit.osgi.ecm.extender.ri.internal.ECMCapabilityTracker.removedBundle(ECMCapabilityTracker.java:103)
    	at org.everit.osgi.ecm.extender.ri.internal.ECMCapabilityTracker.removedBundle(ECMCapabilityTracker.java:43)
    	at org.osgi.util.tracker.BundleTracker$Tracked.customizerRemoved(BundleTracker.java:495)
    	at org.osgi.util.tracker.BundleTracker$Tracked.customizerRemoved(BundleTracker.java:1)
    	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:341)
    	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
    	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:902)
    	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:165)
    	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:75)
    	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:67)
    	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:102)
    	at org.eclipse.osgi.container.Module.publishEvent(Module.java:466)
    	at org.eclipse.osgi.container.Module.doStop(Module.java:624)
    	at org.eclipse.osgi.container.Module.stop(Module.java:488)
    	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1623)
    	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1542)
    	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:248)
    	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:145)
    	at org.eclipse.osgi.container.Module.doStop(Module.java:626)
    	at org.eclipse.osgi.container.Module.stop(Module.java:488)
    	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
    	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:160)
    	at java.lang.Thread.run(Thread.java:745)

**Comment by balazs-zsoldos** [comment]
Probably solved in 1.2.3. Please test it!

**Comment by zsigmond-czine-everit** [comment]
Not solved problem in 1.2.3. Already has NPE while shutting down the OSGi container.

**Comment by balazs-zsoldos** [comment]
Fixed
